"""remove_category_pictogram_sequence_models

Revision ID: 03d3f2ead855
Revises: b75b28d39c68
Create Date: 2025-03-08 08:20:03.938582

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03d3f2ead855'
down_revision = 'b75b28d39c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Use SQL directly to drop tables with CASCADE option
    op.execute('DROP TABLE IF EXISTS sequence_pictogram_positions CASCADE')
    op.execute('DROP TABLE IF EXISTS pictogram_categories CASCADE')
    op.execute('DROP TABLE IF EXISTS sequences CASCADE')
    op.execute('DROP TABLE IF EXISTS sequence_groups CASCADE')
    op.execute('DROP TABLE IF EXISTS pictograms CASCADE')
    op.execute('DROP TABLE IF EXISTS categories CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequences',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_favorite', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='sequences_created_by_fkey'),
    sa.ForeignKeyConstraint(['group_id'], ['sequence_groups.id'], name='sequences_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sequences_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('pictograms',
    sa.Column('word', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_custom', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('lang', sa.VARCHAR(length=10), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='pictograms_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='pictograms_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('sequence_groups',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='sequence_groups_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='sequence_groups_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('pictogram_categories',
    sa.Column('pictogram_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='pictogram_categories_category_id_fkey'),
    sa.ForeignKeyConstraint(['pictogram_id'], ['pictograms.id'], name='pictogram_categories_pictogram_id_fkey'),
    sa.PrimaryKeyConstraint('pictogram_id', 'category_id', name='pictogram_categories_pkey')
    )
    op.create_table('categories',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_custom', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_visible', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='categories_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='categories_pkey')
    )
    op.create_table('sequence_pictogram_positions',
    sa.Column('sequence_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pictogram_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pictogram_id'], ['pictograms.id'], name='sequence_pictogram_positions_pictogram_id_fkey'),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], name='sequence_pictogram_positions_sequence_id_fkey'),
    sa.PrimaryKeyConstraint('sequence_id', 'pictogram_id', name='sequence_pictogram_positions_pkey')
    )
    # ### end Alembic commands ###
