"""add_lang_field_to_user

Revision ID: 340e7554a075
Revises: 03d3f2ead855
Create Date: 2025-03-08 13:45:39.640791

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '340e7554a075'
down_revision = '03d3f2ead855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lang', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lang')
    # ### end Alembic commands ###
