"""remove_foreign_key_from_nome_table

Revision ID: 45a76dcabd8a
Revises: 846b7c19009b
Create Date: 2025-03-02 09:05:01.773185

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '45a76dcabd8a'
down_revision = '846b7c19009b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the foreign key constraint
    op.drop_constraint('nome_pictogram_id_fkey', 'nome', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the foreign key constraint back
    op.create_foreign_key('nome_pictogram_id_fkey', 'nome', 'pictogram', ['pictogram_id'], ['id'])
    # ### end Alembic commands ###
