"""add_fields_to_pecs_categories

Revision ID: 57a62027ccf6
Revises: 340e7554a075
Create Date: 2025-03-08 15:08:04.115746

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '57a62027ccf6'
down_revision = '340e7554a075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pecs_categories', sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('pecs_categories', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('pecs_categories', sa.Column('is_custom', sa.Boolean(), nullable=True))
    op.add_column('pecs_categories', sa.Column('is_visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pecs_categories', 'is_visible')
    op.drop_column('pecs_categories', 'is_custom')
    op.drop_column('pecs_categories', 'color')
    op.drop_column('pecs_categories', 'icon')
    # ### end Alembic commands ###
