"""add_name_custom_field_to_pecs_and_category

Revision ID: 752dc737c08d
Revises: 279319d908ce
Create Date: 2025-03-14 15:49:27.275137

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '752dc737c08d'
down_revision = '279319d908ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pecs', sa.Column('name_custom', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('pecs_categories', sa.Column('name_custom', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pecs_categories', 'name_custom')
    op.drop_column('pecs', 'name_custom')
    # ### end Alembic commands ###
