"""add origin field to phrase_pecs

Revision ID: 93cdd480f5ce
Revises: afa4ff3971fb
Create Date: 2025-03-31 21:27:15.798751

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '93cdd480f5ce'
down_revision = 'afa4ff3971fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phrase_pecs', sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phrase_pecs', 'origin')
    # ### end Alembic commands ###
