"""add_lang_field_to_pictogram

Revision ID: 9d5f2a7e4b38
Revises: 8db1da7e3926
Create Date: 2025-03-06 13:47:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9d5f2a7e4b38'
down_revision = '8db1da7e3926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictograms', sa.Column('lang', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False, server_default='en'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pictograms', 'lang')
    # ### end Alembic commands ###