"""Add cascade delete to pictogram relations

Revision ID: add_cascade_delete_to_pictogram_relations
Revises: cbd2cad966bc
Create Date: 2025-03-06 15:09:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'add_cascade_pictogram_rel'
down_revision = 'cbd2cad966bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Rimuovi la chiave esterna esistente
    op.drop_constraint('pictogram_categories_pictogram_id_fkey', 'pictogram_categories', type_='foreignkey')
    
    # Ricrea la chiave esterna con l'opzione ON DELETE CASCADE
    op.create_foreign_key(
        'pictogram_categories_pictogram_id_fkey', 
        'pictogram_categories', 
        'pictograms', 
        ['pictogram_id'], 
        ['id'], 
        ondelete='CASCADE'
    )
    
    # Fai lo stesso per sequence_items
    op.drop_constraint('sequence_items_pictogram_id_fkey', 'sequence_items', type_='foreignkey')
    op.create_foreign_key(
        'sequence_items_pictogram_id_fkey', 
        'sequence_items', 
        'pictograms', 
        ['pictogram_id'], 
        ['id'], 
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Ripristina le chiavi esterne originali senza l'opzione ON DELETE CASCADE
    op.drop_constraint('pictogram_categories_pictogram_id_fkey', 'pictogram_categories', type_='foreignkey')
    op.create_foreign_key(
        'pictogram_categories_pictogram_id_fkey', 
        'pictogram_categories', 
        'pictograms', 
        ['pictogram_id'], 
        ['id']
    )
    
    op.drop_constraint('sequence_items_pictogram_id_fkey', 'sequence_items', type_='foreignkey')
    op.create_foreign_key(
        'sequence_items_pictogram_id_fkey', 
        'sequence_items', 
        'pictograms', 
        ['pictogram_id'], 
        ['id']
    )
    # ### end Alembic commands ###