"""add_pecs_tables

Revision ID: b75b28d39c68
Revises: 9e7bb07f125d
Create Date: 2025-03-08 08:12:35.226778

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b75b28d39c68'
down_revision = '9e7bb07f125d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pecs_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['pecs_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories_translations',
    sa.Column('language_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['pecs_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pecs',
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phrases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_pecs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pecs_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['pecs_id'], ['pecs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'pecs_id')
    )
    op.create_table('favorite_phrases',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('phrase_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'phrase_id')
    )
    op.create_table('pecs_category_items',
    sa.Column('pecs_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['pecs_categories.id'], ),
    sa.ForeignKeyConstraint(['pecs_id'], ['pecs.id'], ),
    sa.PrimaryKeyConstraint('pecs_id', 'category_id')
    )
    op.create_table('pecs_translations',
    sa.Column('language_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pecs_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['pecs_id'], ['pecs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phrase_pecs',
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('phrase_id', sa.Uuid(), nullable=False),
    sa.Column('pecs_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['pecs_id'], ['pecs.id'], ),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrases.id'], ),
    sa.PrimaryKeyConstraint('phrase_id', 'pecs_id')
    )
    op.create_table('phrases_translations',
    sa.Column('language_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phrase_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phrases_translations')
    op.drop_table('phrase_pecs')
    op.drop_table('pecs_translations')
    op.drop_table('pecs_category_items')
    op.drop_table('favorite_phrases')
    op.drop_table('favorite_pecs')
    op.drop_table('phrases')
    op.drop_table('pecs')
    op.drop_table('categories_translations')
    op.drop_table('pecs_categories')
    # ### end Alembic commands ###
