"""add_lang_field_to_pictogram

Revision ID: da3a23aaf58a
Revises: 9d5f2a7e4b38
Create Date: 2025-03-06 13:48:58.206678

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'da3a23aaf58a'
down_revision = '9d5f2a7e4b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
